apiVersion: v1beta3
kind: Service
metadata:
  name: app-etcd-service
spec:
  ports:
    - port: 2379
      name: clientport
      targetPort: listen-client-port
    - port: 2380
      name: servertoserverport
      targetPort: peer-port
  selector:
    name: app-etcd
