apiVersion: v1
kind: Service
metadata:
  name: app-etcd-service
spec:
  ports:
    - port: 2379
      name: client
      targetPort: client
    - port: 2380
      name: peer
      targetPort: peer
  selector:
    name: app-etcd
