apiVersion: v1beta3
kind: Service
metadata:
  name: app-etcd-service
spec:
  ports:
    - port: 2379
      name: clientport
      targetPort: 2379
      protocol: TCP
    - port: 2380
      name: servertoserverport
      targetPort: 2380
      protocol: TCP
  selector:
    name: app-etcd
