apiVersion: v1
kind: Service
metadata:
  name: couchbase-admin-service
spec:
  ports:  # see http://docs.couchbase.com/admin/admin/Install/install-networkPorts.html
    - port: 8091
      name: admin
      targetPort: admin
    - port: 8092
      name: views
      targetPort: views
  type: "LoadBalancer"
  # just like the selector in the replication controller,
  # but this time it identifies the set of pods to load balance
  # traffic to.
  selector:
    name: couchbase-server
    role: admin
