apiVersion: v1beta3
kind: ReplicationController
metadata:
  name: couchbase-controller
spec:
  replicas: 2
  # selector identifies the set of Pods that this
  # replicaController is responsible for managing
  selector:
    name: couchbase-server
  # podTemplate defines the 'cookie cutter' used for creating
  # new pods when necessary
  template:
    metadata:
      labels:
        # Important: these labels need to match the selector above
        # The api server enforces this constraint.
        name: couchbase-server
    spec:
      containers:
        - name: couchbase-server
          image: couchbase/server
          ports:
            - containerPort: 8091
              hostPort: 8091

