apiVersion: v1beta3
kind: ReplicationController
metadata:
  name: sync-gateway
spec:
  replicas: 2
  # selector identifies the set of Pods that this
  # replicaController is responsible for managing
  selector:
    name: sync-gateway
  # podTemplate defines the 'cookie cutter' used for creating
  # new pods when necessary
  template:
    metadata:
      labels:
        # Important: these labels need to match the selector above
        # The api server enforces this constraint.
        name: sync-gateway
    spec:
      containers:
        - name: sync-gateway
          image: couchbase/sync-gateway
          command:
            - sync_gateway
            - { "log": ["*"], "databases": { "db": { "server": "http://$COUCHBASE_SERVER_SERVICE_HOST:8091", "bucket": "default", "users": { "GUEST": { "disabled": false, "admin_channels": ["*"] } } } } }
          ports:
            - containerPort: 4984
            - containerPort: 4985

