apiVersion: v1beta3
kind: ReplicationController
metadata:
  name: sync-gateway
spec:
  replicas: 2
  # selector identifies the set of Pods that this
  # replicaController is responsible for managing
  selector:
    name: sync-gateway
  # podTemplate defines the 'cookie cutter' used for creating
  # new pods when necessary
  template:
    metadata:
      labels:
        # Important: these labels need to match the selector above
        # The api server enforces this constraint.
        name: sync-gateway
    spec:
      containers:
        - name: sync-gateway
          image: couchbase/sync-gateway
          command:
            - /bin/sh
            - -c
            - wget -O /sync-gateway-data/sync-gateway.config https://raw.githubusercontent.com/couchbase/kubernetes/master/config/sync-gateway.config && sed -i "s/\$COUCHBASE_SERVICE_SERVICE_HOST/$COUCHBASE_SERVICE_SERVICE_HOST/" /sync-gateway-data/sync-gateway.config && sync_gateway /sync-gateway-data/sync-gateway.config
            rts:
            - containerPort: 4984
            - containerPort: 4985
          volumeMounts:
            - mountPath: /sync-gateway-data
              name: data
      volumes:
        - name: data
          emptyDir: {}

