apiVersion: v1
kind: ReplicationController
metadata:
  name: sync-gateway
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  replicas: 2
  # selector identifies the set of Pods that this
  # replicaController is responsible for managing
  selector:
    name: sync-gateway
  # podTemplate defines the 'cookie cutter' used for creating
  # new pods when necessary
  template:
    metadata:
      labels:
        # Important: these labels need to match the selector above
        # The api server enforces this constraint.
        name: sync-gateway
    spec:
      containers:
        - name: sync-gateway
          image: couchbase/sync-gateway:2.5.1-community
          # TODO: rewrite this to modify config file to requested namespace - instead of just pulling from github 
          #       - which means pushing config file in as configmap - and mounting in pod and giving that path instead
          command:
            - sync_gateway
            - https://raw.githubusercontent.com/klavsklavsen/couchbase-kubernetes/master/config/sync-gateway.config
          ports:
            - containerPort: 4984
            - containerPort: 4985
