apiVersion: v1beta3
kind: Pod
metadata:
  name: app-etcd
spec:
  containers:
    - name: app-etcd
      image: tleyden5iwx/etcd-discovery
      command:
        - etcdisco
        - -listen-client-urls
        - http://0.0.0.0:2379
        - -advertise-client-urls
        - http://{{.LOCAL_IP}}:2379
      ports:
        -
          containerPort: 2379
          hostPort: 2379
        -
          containerPort: 2380
          hostPort: 2380
