apiVersion: v1
kind: Pod
metadata:
  name: app-etcd
  labels:
    name: app-etcd
spec:
  containers:
    - name: app-etcd
      image: tleyden5iwx/etcd-discovery
      command:
        - etcdisco
        - -listen-client-urls
        - http://0.0.0.0:2379
        - -advertise-client-urls
        - http://{{.LOCAL_IP}}:2379
      ports:
        - name: client
          containerPort: 2379
        - name: peer
          containerPort: 2380